apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-kanban-app
spec:
  params:
    - name: image-name
      description: Name of the image to build
      default: "kanban-app"
  steps:
    - name: echo-message
      image: alpine
      script: |
        #!/bin/sh
        echo "Building Kanban Application"
        echo "Image: $(params.image-name)"
        echo "Starting build process..."
        sleep 2
        echo "Build completed successfully!"
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: test-kanban-app
spec:
  steps:
    - name: run-tests
      image: python:3.11-slim
      script: |
        #!/bin/sh
        echo "Running unit tests..."
        echo "Test 1: API endpoint test - PASSED"
        echo "Test 2: Database connection test - PASSED"
        echo "Test 3: CRUD operations test - PASSED"
        sleep 2
        echo "All tests passed successfully!"
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy-kanban-app
spec:
  params:
    - name: deployment-name
      description: Name of the deployment
      default: "kanban-deployment"
  steps:
    - name: deploy
      image: alpine
      script: |
        #!/bin/sh
        echo "Deploying application: $(params.deployment-name)"
        echo "Checking Kubernetes cluster..."
        sleep 1
        echo "Applying deployment configuration..."
        sleep 2
        echo "Deployment successful!"
        echo "Application is now running on Kubernetes"
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: kanban-pipeline
spec:
  params:
    - name: image-name
      type: string
      default: "kanban-app"
    - name: deployment-name
      type: string
      default: "kanban-deployment"
  tasks:
    - name: build
      taskRef:
        name: build-kanban-app
      params:
        - name: image-name
          value: $(params.image-name)
    - name: test
      taskRef:
        name: test-kanban-app
      runAfter:
        - build
    - name: deploy
      taskRef:
        name: deploy-kanban-app
      params:
        - name: deployment-name
          value: $(params.deployment-name)
      runAfter:
        - test
